# Generated by Django 5.0.6 on 2024-07-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmend', '0002_remove_scores_selected_emotions_remove_scores_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='score',
            name='selected_emotions',
        ),
        migrations.AddField(
            model_name='score',
            name='emotions',
            field=models.ManyToManyField(to='mindmend.emotion'),
        ),
        migrations.AlterField(
            model_name='score',
            name='general_emotion_value',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
        migrations.AlterField(
            model_name='score',
            name='image_value',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
        migrations.AlterField(
            model_name='score',
            name='revaluation_one',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
        migrations.AlterField(
            model_name='score',
            name='revaluation_two',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
    ]
